---

- name: Domain Provision
  ansible.builtin.shell: |
    samba-tool domain provision --domain={{ SAMBA_DC_DOMAIN}} \
    --adminpass={{ SAMBA_DC_ADMIN_PASSWD }} \
    --server-role=dc \
    --realm={{ SAMBA_DC_REALM }} \
    --dns-backend="SAMBA_INTERNAL" \
    --use-rfc2307 \
    --option="interfaces=lo {{ ansible_default_ipv4.interface }}" \
    --option="bind interfaces only=yes"