# -*- mode: ruby -*-
# vi: set ft=ruby :

# Quantidade de máquinas que irão subir
NODE_COUNT = 1
BOX_IMAGE = "ybucci/centos8"

Vagrant.configure("2") do |config|

  (1..NODE_COUNT).each do |i|
    config.vm.define "node#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.hostname = "node#{i}"
      # Range de IP a ser utilizado e Interface de rede
      subconfig.vm.network :public_network, ip: "192.168.18.#{i + 129}", bridge: "Realtek Gaming GbE Family Controller #2"
      subconfig.vm.disk :disk, size: "50GB", name: "extra_storage#{i + 2}"
      subconfig.vm.disk :disk, size: "50GB", name: "extra_storage#{i + 3}"
      subconfig.vm.synced_folder '.', '/vagrant', disabled: true
    end
    config.vm.provider "virtualbox" do |v|
      #Configura memória e vCPUS das máquinas
      v.memory = 2048
      v.cpus = 2 
    end    
  end
  # Install avahi on all machines  
  config.vm.provision "shell", inline: <<-SHELL
    # Rota do seu gateway padrão
    yum install net-tools -y
    route add default gw 192.168.18.1
  SHELL
end
