---

# Create Folders

- name: Create Users Directory
  ansible.builtin.file:
    path: "{{ FILESERVER.SHARE_PATH }}/Users"
    state: directory
  when: FILESERVER.ENABLE_HOME_SHARE and not SHADOW_COPY_ENABLE

- name: Create Public Directory
  ansible.builtin.file:
    path: "{{ FILESERVER.SHARE_PATH }}/Public"
    state: directory
  when: FILESERVER.ENABLE_PUBLIC_SHARE and not SHADOW_COPY_ENABLE

# Chown Folders

- name: Change Users group ownership
  ansible.builtin.file:
    path: "{{ FILESERVER.SHARE_PATH }}/Users"
    state: directory
    owner: root
    group: "Domain Admins"
  when: FILESERVER.ENABLE_HOME_SHARE

- name: Change Public group ownership
  ansible.builtin.file:
    path: "{{ FILESERVER.SHARE_PATH }}/Public"
    state: directory
    owner: root
    group: "Domain Admins"
  when: FILESERVER.ENABLE_PUBLIC_SHARE

# Home User

- name: Set ACL of Home Users Folder
  ansible.builtin.shell: samba-tool ntacl set "O:LAG:DAD:PAI(A;OICI;0x001f01ff;;;LA)(A;OICI;0x001f01ff;;;DA)(A;OICIIO;0x001f01ff;;;CO)(A;;0x001200a9;;;DU)" {{ FILESERVER.SHARE_PATH }}/Users
  when: FILESERVER.ENABLE_HOME_SHARE

# Public

- name: Set ACL of Public Folder
  ansible.builtin.shell: samba-tool ntacl set "O:LAG:DAD:PAI(A;;0x001f01ff;;;LA)(A;;0x001f01ff;;;DA)(A;OICIIO;0x001301bf;;;CO)(A;OICIIO;0x001301bf;;;CG)(A;OICI;0x001301bf;;;DU)" {{ FILESERVER.SHARE_PATH }}/Public
  when: FILESERVER.ENABLE_PUBLIC_SHARE