# -*- mode: ruby -*-
# vi: set ft=ruby :

NODE_COUNT = 1
BOX_IMAGE = "gusztavvargadr/windows-11"

Vagrant.configure("2") do |config|

  (1..NODE_COUNT).each do |i|
    config.vm.define "nodews#{i}" do |subconfig|
      subconfig.vm.box = BOX_IMAGE
      subconfig.vm.guest = :windows
      subconfig.vm.communicator = "winrm"
      subconfig.vm.boot_timeout = 600
      subconfig.vm.graceful_halt_timeout = 600
      subconfig.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
      subconfig.vm.hostname = "nodew#{i}"
      subconfig.vm.network :public_network, ip: "192.168.15.#{i + 141}", bridge: "Intel(R) Wi-Fi 6 AX200 160MHz"
      subconfig.vm.synced_folder '.', '/vagrant', disabled: true
    end
    config.vm.provider "virtualbox" do |v|
      v.memory = 3200
      v.cpus = 2
    end    
  end
end
